#ifndef CLIENTSERVERINTERFACE_GLOBAL_H
#define CLIENTSERVERINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLIENTINTERFACE_LIBRARY)
#  define CLIENTINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLIENTINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#if defined(SERVERINTERFACE_LIBRARY)
#  define SERVERINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLIENTSERVERINTERFACE_GLOBAL_H

