#ifndef QFILEEXTENSIONS_GLOBAL_H
#define QFILEEXTENSIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QFILEEXTENSIONS_LIBRARY)
#  define QFILEEXTENSIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QFILEEXTENSIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QFILEEXTENSIONS_GLOBAL_H

