#ifndef SERVERDATABASE_GLOBAL_H
#define SERVERDATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERDATABASE_LIBRARY)
#  define SERVERDATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERDATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERDATABASE_GLOBAL_H

